laravel/serializable-closure

src/SerializableClosure.php

Note the inclusion of the leading slash too. Opcache is actually able to evaluate the guard at compile-time!

Compare against `PHP_VERSION_ID` instead

---

.github/ISSUE_TEMPLATE/1_Bug_report.md
.github/ISSUE_TEMPLATE/2_Feature_request.md
.github/ISSUE_TEMPLATE/config.yml
README.md
phpstan.neon
src/Serializers/Native.php
src/Signers/Hmac.php
src/Support/ClosureStream.php
src/Support/ReflectionClosure.php

Updates to default files

---

src/Support/ReflectionClosure.php

FIxed the failing test in #16 using xdebug on php 8.0.11 it turns out that we missed a token

Fix use of nullsafe operator failing test

---

src/Support/ReflectionClosure.php
tests/ReflectionClosurePhp80Test.php

This pull request is a work in progress. At this time, it contains a failing test.
https://github.com/laravel/framework/issues/38903

Fixes null safe operator with properties

---

src/Serializers/Native.php
tests/SerializerTest.php

This pull request fixes serialization closures that got rebounded. There was missing a "from" method.
Fixes #18

[1.x] Fixes rebound closures serialization

---

src/Serializers/Native.php
tests/ReflectionClosurePhp81Test.php
tests/SerializerPhp81Test.php

This pull request fixes the serialization of Enum objects when those are imported via `use` or via `scope` on short closures.
Fixed #27.

Fixes the serialization of `Enum` objects

---

phpunit.xml.dist
src/Support/ReflectionClosure.php
tests/ReflectionClosurePhp80Test.php
tests/SerializerPhp80Test.php
tests/SerializerPhp81Test.php

This pull request closes https://github.com/laravel/serializable-closure/issues/30, by fixing the serialisation of named arguments.

[1.x] Fixes serialisation of closures with named arguments code

---

src/Support/ReflectionClosure.php
tests/ReflectionClosurePhp81Test.php
tests/SerializerPhp81Test.php

This pull request adds support for first class callable syntax.
Because the first class callable syntax result does not "look" like a regular closure when serialised, this pull request attempts to transform the result of the code to a regular closure. Let me show you some examples:
```php
// Assuming...
class Person {
public function getName1() {}
final public function getName2() {}
public static function getName3() {}
}
// Assuming the following syntax, used within the Person class...
$1 = $this->getName1(...);
$2 = $this->getName2(...);
$2 = $this->getName3(...);
// The variables `$1`, `$2` and `$3`, when serialised / deserialised:
$1 = function () {} // bound to Person instance
$2 = function () {} // bound to Person instance
$3 = static function () {} // statically bound to Person …
```

[1.x] Adds support for first class callable syntax

---

.github/workflows/update-changelog.yml

Use the target branch of a release in the compare URL when updating the changelog through GitHub Actions.

Use release target branch in changelog compare URL

---

src/Support/ReflectionClosure.php
tests/Fixtures/Model.php
tests/ReflectionClosure5Test.php
tests/ReflectionClosurePhp81Test.php
tests/SerializerPhp81Test.php
tests/SerializerTest.php

This pull request fixes the serialisation of first class callable closures. As the full qualified namespaces were not being used on types.
Closes https://github.com/laravel/serializable-closure/pull/38.
In other words:
```php
// giving the code
namespace App\Models;
class User { function getUser(): User {} };
// and the serialisation of
$user->getUser(...);
// before 🛑
return function (): User {}
// after ✅
return function (): \App\Models\User {}
```

[1.x] Fixes first class callables namespaces

---

README.md
src/Support/ReflectionClosure.php
tests/Fixtures/ModelAttribute.php
tests/ReflectionClosurePhp81Test.php
tests/SerializerPhp81Test.php

This pull request adds function attributes support to serialisable closures:
```php
#[Attribute(Attribute::TARGET_FUNCTION)]
class MyAttribute
{
// ..
}
$closure = #[MyAttribute('My attribute argument')] function () {
return true;
};
$closure = unserialize(serialize($closure))->getClosure();
// Before this pull request:
dd(new ReflectionFunction($closure))->getAttributes());
// []
// After this pull request:
dd(new ReflectionFunction($closure))->getAttributes());
// [['name' => 'MyAttribute', 'arguments' => ['My attribute argument']]]
```

Adds Function Attributes support

---

src/Serializers/Native.php
tests/SerializerPhp81Test.php

Fixes #43 
This PR fixes a bug when trying to serialize a closure that was defined inside a class where any class in its context has a property containing an enum. Since that's quite a mouthful, here's an example.
Given these enum and class declarations:
```php
enum MyEnum
{
case Foo;
case Bar;
}
class MyClass
{
public MyEnum $enum = MyEnum::Foo;
public Closure $closure;
public function __construct()
{
$this->closure = function () {
return $this->enum;
};
}
}
```
A couple important things to point out:
- The class `MyClass` has a property with an enum as its value. It's not actually important that this field exists on `MyClass` specifically. As long as some class _somewhere_ in the closure's context has a property with an enum as its value, the bug will still occur. So if `MyClass` had a …

Adds support for closure inside context with enum property

---

src/Serializers/Native.php
tests/ReflectionClosure1Test.php
tests/SerializerTest.php

Reopen: https://github.com/laravel/serializable-closure/pull/52

fix: serializing date and carbon objects

---

composer.json
src/Serializers/Native.php
tests/SerializerTest.php

This is related to https://github.com/laravel/serializable-closure/pull/53, but that fix did not work for the issue I was having with Carbon serialization.
Like that PR, the specific error I am getting is "The DateTime object has not been correctly initialized by its constructor".
This test does fail when the fix is commented out.
I decided to check for an instance of DateTime instead of Carbon specifically since it seems like others are having an issue with DateTime objects. However, I could not replicate the issue with a plain DateTime object, that's why I included the dev dependency of Carbon.
This issue informed the fix: https://github.com/laravel/framework/issues/43695

Fix serialization of carbon objects

---

README.md

This pull request clarifies that is not possible to serialize closures on REPL environments.

[1.x] Clarifies serialization on REPL environments

---

src/SerializableClosure.php
src/UnsignedSerializableClosure.php

This adds a new parameter to specify if a closure should be signed or not.
When caching routes in the Laravel/framework, they are currently being cached signed. This means if you cache your routes and then set/change your `APP_KEY` your route caches are invalid.
This option allows the route caching logic to disable signing when caching the routes, which then means `APP_KEY` can be changed without the route caching being invalid.
When building a docker image it is currently impossible to cache your routes while building the image (if any routes are closures) as the `APP_KEY` should not be exposed to the build steps of the docker image.  
Caching the routes while building the image has a lot of advantages, as each instance does not have to cache it themselves. This can also prevent …

feat: Add support for specifying if it should sign

---

src/SerializableClosure.php
src/Serializers/Native.php
tests/Datasets/Serializers.php
tests/Pest.php
tests/Php73Test.php
tests/SerializerTest.php

This pull request:
1. Runs the test suite against the new `UnsignedSerializableClosure`.
2. Lets `SerializableClosure` act as a factory and create `UnsignedSerializableClosure` using the static factory `SerializableClosure::unsigned`.
3. Fixes a bug in `src/Serializers/Native.php` where serializing `UnsignedSerializableClosure` could cause runtime exceptions if it had properties from the type `UnsignedSerializableClosure`.

[1.x] Fixes and tests unsigned closures

---

README.md

This pull request adds documentation about `readonly` caveat.

[1.x] Adds documentation about `readonly` caveat

---

src/Support/ReflectionClosure.php
tests/ReflectionClosure5Test.php

Code
```
use Foo\Bar;
$closure = fn() => new class() extends Bar\Baz {
};
$reflector = new ReflectionClosure($closure);
echo $reflector->getCode();
```
Current result:
```
fn() => new class() extends Bar\Baz {
}
```
Expected result:
```
fn() => new class() extends \Foo\Bar\Baz {
}
```

Fix `getCode` when returning anonymous class extending/implementing non FQCN.

---

src/Support/ReflectionClosure.php
tests/ReflectionClosure5Test.php

This pull request fixes the usage of FQCN on anonymous classes definition. It contains the contents of https://github.com/laravel/serializable-closure/pull/74, but I've added some more tests.

[1.x] Fixes FQCN on anonymous classes definition 

---

src/Support/ReflectionClosure.php
tests/ReflectionClosure1Test.php
tests/ReflectionClosurePhp80Test.php
tests/ReflectionClosurePhp81Test.php
tests/SerializerPhp80Test.php
tests/SerializerTest.php

This pull request fixes https://github.com/laravel/serializable-closure/issues/78, witch is related to the usage of switch cases cases combined with namespace resolution.
So, prior to this pull request, the following scenario was not possible:
```php
use Laravel\Scout\Searchable;
Route::get('show', function (User|Product $model) {
switch(true) {
$user instanceof Searchable: // bug here, because Searchable was not converted to $user instanceof \Laravel\Scout\Searchable;
return view('search-view');
return view('regular');
});
```

[1.x] Fixes switch cases namespace resolution

---

src/Serializers/Native.php
tests/SerializerPhp81Test.php

This pull request fix [this issue](https://github.com/laravel/framework/issues/51877) where an exception is thrown during the unserialize process when `Bus::chain` handles a class that includes a readonly property. The exception message is: `Cannot modify readonly property Illuminate\Tests\Integration\Queue\ReadonlyEnumTestJob::$enum`.

Fix bug related to readonly properties

---

src/Support/ReflectionClosure.php

This pull request fixes PHP 8.4 support in this package; the issue was: closures without any namespace were being considered first class callables (aka `class::method(...)`).

[2.x] Fix namespaced closures being considered first class callables

---

phpunit.xml.dist

The develop branch requires PHP 8.1, therefor the phpunit.xml can be simplified.

[2.x] Cleanup phpunit.xml

---

src/Serializers/Native.php
tests/SerializerPhp81Test.php

If you try to serialize an object that has readonly properties that declared in parent, you will get an error "Cannot initialize readonly property Parent::$property from scope Child". This PR fixes this
```php
class Parent
{
public function __construct(
public readonly int $property = 1,
) {}
}
class Child extends Parent {}
$object = new Child();
$closure = static fn () => $object;
serialize(new \Laravel\SerializableClosure\SerializableClosure($closure));
```

Fix for readonly properties that declared in parent
